# Generated by Django 3.2 on 2021-04-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
