# Generated by Django 3.2 on 2021-04-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210418_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
