# Generated by Django 3.2 on 2021-04-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
