# Generated by Django 3.2 on 2021-05-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_friendlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
