# Generated by Django 3.2 on 2021-05-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_profile_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='donation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
