# Generated by Django 3.2 on 2021-05-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_auto_20210503_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='next_donation_date',
            field=models.DateField(null=True),
        ),
    ]
