# Generated by Django 3.2 on 2021-05-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_profile_next_donation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='post_images')),
            ],
        ),
    ]
