# Generated by Django 3.2 on 2021-05-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
