# Generated by Django 3.2 on 2021-05-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='donation_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='next_donation_date',
        ),
        migrations.CreateModel(
            name='Donation_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(null=True)),
                ('next_donation_date', models.DateField(null=True)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.profile')),
            ],
        ),
    ]
