# Generated by Django 3.2 on 2021-05-16 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0014_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 5, 16, 14, 59, 39, 15930, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
