# Generated by Django 3.2 on 2021-05-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0017_userpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='title',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='content',
        ),
    ]
