# Generated by Django 3.2 on 2021-05-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0018_auto_20210516_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='image',
            field=models.ImageField(null=True, upload_to='User_post/images'),
        ),
    ]
