# Generated by Django 3.2 on 2021-05-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0021_alter_userpost_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='user_post'),
        ),
    ]
