# Generated by Django 3.2 on 2021-05-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0022_auto_20210518_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
