# Generated by Django 3.2 on 2021-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0023_auto_20210518_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
