# Generated by Django 3.2 on 2021-05-18 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0026_auto_20210518_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='donation.comments'),
        ),
    ]
