# Generated by Django 3.2 on 2021-05-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0029_alter_userpost_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.comments'),
        ),
    ]
