# Generated by Django 3.2 on 2021-05-18 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0030_alter_userpost_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.userpost'),
        ),
    ]
